### ISSUE TITLE
JComboBox not working with Java 6?

### ISSUE THREAD

**Issue by Sciss** [mgarin/weblaf#360] opened 2016-03-06 21:55 UTC
I notice a problem with the demo: When using OpenJDK 6 (1.6.0_31), it's not possible to select items in the popup menu from the skin-selector combo-box with the mouse. Only keyboard control is possible. When running under OpenJDK 7 (1.7.0_95) or Oracle JDK 8 (1.8.0_72), operating the combo box is no problem.

It doesn't seem to be a general problem with JComboBox, though. A minimal case works fine under all Java versions:

``` java
package com.alee.demo;

import com.alee.laf.WebLookAndFeel;

import javax.swing.*;
import java.awt.*;

public class ComboTest implements Runnable {
    public static void main(String[] args) {
        EventQueue.invokeLater(new ComboTest());
    }

    public void run() {
        WebLookAndFeel.install();
        final JFrame f = new JFrame("Test");
        f.getContentPane().add(new JComboBox(new String[] { "One", "Two", "Three" }));
        f.pack();
        f.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        f.setVisible(true);
    }
}
```

**Comment by iamchathu** [comment] 2016-03-07 04:10
It's working on Oracle JDK 1.7

**Comment by mgarin** [comment] 2016-03-07 15:32
This might be something tied to window manipulations on OpenJDK 6, but can't say for sure. OpenJDK 6 had quite a few problems due to slightly different way of handling painting and different basic UI code. I have solved a few of those issues long time ago, but new ones are probably there now because of the large changes scale.

I will have a closer look at OpenJDK 6 a bit later, but my general recommendation for now - use Oracle JDK instead if it is possible.

**Comment by mgarin** [comment] 2020-07-27 14:52
Better later than never :)

To be honest - I weren't able to find 1.6.0_31 OpenJDK build, so I've checked it on the only Open JDK 6 build I managed to find:
https://www.azul.com/downloads/zulu-community/?version=java-6-lts&architecture=x86-64-bit&package=jdk

It seems to work correctly, both under Windows & Ubunutu on WebLaF v1.2.13. It might have been an issue related to specific WebLaF version (in which case it is fixed), OpenJDK version or build (in which case it's probably not that relevant anymore).

I'll be closing this for now, but if it's still an issue you encounter in demo - feel free to reopen, but provide information on where I can get the same Open JDK build you're using to reproduce it.

**Closed by mgarin** 2020-07-27 14:52 UTC
Labels: Open JDK 6, bug
