### ISSUE TITLE
how to select a checkbox programmatically in WebCheckBoxList

### ISSUE THREAD

**Issue by mokun** [mgarin/weblaf#592] opened 2019-12-02 18:11 UTC
I cannot select a checkbox programmatically in `WebCheckBoxList`

`WebCheckBoxList settlementMissionList = new WebCheckBoxList<>(StyleId.checkboxlist, createModel(getOtherSettlements()));
`

I set up the WebCheckBoxList based on an example from the demo.

```
    /**
     * Returns sample check box list model.
     *
     * @param data sample data
     * @return sample check box list model
     */
    protected static CheckBoxListModel<?> createModel (final List<Settlement> settlements) {
        final CheckBoxListModel<?> model = new CheckBoxListModel();
        for (final Settlement element : settlements) {
            model.add(new CheckBoxCellData(element));
        }
        return model;
    }

```

I tried to call `setCheckBoxSelected(i, false)` to programmatically change the check box back to empty if it doesn't work. 

The checkboxes can only be changed by user's mouse action.

How do I **clear** all the checkboxes ?

```
	public void disableAllCheckedSettlement() {
		List<?> allowedSettlements = settlementMissionList.getCheckedValues();
		int size = allowedSettlements.size();
		for (int i=0; i<size; i++) {
			if (settlementMissionList.isCheckBoxSelected(i)) {
				Settlement s = (Settlement) allowedSettlements.get(i);
				settlementMissionList.setCheckBoxSelected(i, false);
				settlement.setAllowTradeMissionFromASettlement(s, false);
			}	
		}
	}
```

**Comment by mgarin** [comment] 2019-12-03 09:45
> I tried to call setCheckBoxSelected(i, false) to programmatically change the check box back to empty if it doesn't work.

It should work, but maybe something got broken with one of updates - I will check this and see what happens there.

**Comment by mgarin** [comment] 2019-12-04 10:16
Here is a simple test case I've tried and it seem to work properly:
```java
public class CheckBoxListTest
{
    public static void main ( final String[] args )
    {
        SwingTest.run ( new Runnable ()
        {
            @Override
            public void run ()
            {
                final CheckBoxListModel model = new CheckBoxListModel ();
                model.add ( new CheckBoxCellData ( "Sample 1" ) );
                model.add ( new CheckBoxCellData ( "Sample 2" ) );
                model.add ( new CheckBoxCellData ( "Sample 3" ) );

                final WebCheckBoxList list = new WebCheckBoxList ( StyleId.checkboxlist, model );

                list.setCheckBoxSelected ( 0, true );
                list.setCheckBoxSelected ( 1, false );
                list.setCheckBoxSelected ( 2, true );

                TestFrame.show ( list );

                list.onKeyPress ( Hotkey.CTRL_A, new KeyEventRunnable ()
                {
                    @Override
                    public void run ( @NotNull final KeyEvent e )
                    {
                        for ( int i = 0; i < list.getModel ().getSize (); i++ )
                        {
                            list.setCheckBoxSelected ( i, false );
                        }
                    }
                } );
            }
        } );
    }
}
```

Is there anything special about your model?
Maybe some other settings or customization you're using for your list?

**Comment by mokun** [comment] 2019-12-04 20:57
I just found out `setCheckBoxSelected()` works as expected, but `isCheckBoxSelected(i)` don't work, at least in my app.

> Is there anything special about your model?

Nothing special really.



```
	public void disableAllCheckedSettlement() {
		List<?> allowedSettlements = settlementMissionList.getCheckedValues();
		int size = allowedSettlements.size();
		System.out.println(allowedSettlements);
		for (int i=0; i<size; i++) {
//			if (settlementMissionList.isCheckBoxSelected(i)) {
				Settlement s = (Settlement) allowedSettlements.get(i);
				System.out.println("i : " + i + "  " + s);
				settlementMissionList.setCheckBoxSelected(i, false);
				settlement.setAllowTradeMissionFromASettlement(s, false);
//			}	
		}
	}
```

So, when I comment out that if condition as shown above, everything works.

I wonder why `isCheckBoxSelected()` doesn't return `true` even if the box is checked.

```
    /**
     * Returns whether checkbox under the specified cell index is selected or not.
     *
     * @param index cell index
     * @return true if checkbox at the specified cell index is selected, false otherwise
     */
    public boolean isCheckBoxSelected ( final int index )
    {
        return getCheckBoxListModel ().isCheckBoxSelected ( index );
    }
```

**Comment by mokun** [comment] 2019-12-04 21:26
I have more info now.

The culprit is the EDT.

It turns out both `setCheckBoxSelected` and `isCheckBoxSelected()` don't work well and don't give CONSISTENT results without wrapping them in EDT.

After I wrap both  `setCheckBoxSelected` and `isCheckBoxSelected()` in `SwingUtilities.invokeLater()`, they work well now.

See button r3 below : 

```
	class PolicyRadioActionListener implements ActionListener {
	    @Override
	    public void actionPerformed(ActionEvent event) {
	        JRadioButton button = (JRadioButton) event.getSource();
	 
	        if (button == r0) {
	        	settlement.setMissionDisable(Trade.DEFAULT_DESCRIPTION, false);
	        } else if (button == r1) {
	        	settlement.setMissionDisable(Trade.DEFAULT_DESCRIPTION, true);
	        } else if (button == r2) {
	        	SwingUtilities.invokeLater(() -> {
					r3.setText(ALLOW);
					System.out.println("r2 selected");
		        	disableAllCheckedSettlement();
	//	        	settlementMissionList.setEnabled(false);
					policyMainPanel.remove(WebScrollPane);
					policyMainPanel.add(emptyPanel, BorderLayout.EAST);
	        	});
	        } else if (button == r3) {
//	        	settlementMissionList.setEnabled(true);
				r3.setText(ALLOW + SEE_RIGHT);
				policyMainPanel.remove(emptyPanel);
				policyMainPanel.add(WebScrollPane, BorderLayout.EAST);
	        }
	    }
	}
```

**Comment by mgarin** [comment] 2019-12-05 10:13
I've added this piece to the example I've posted above:
```java
list.onKeyPress ( Hotkey.CTRL_F, new KeyEventRunnable ()
{
    @Override
    public void run ( @NotNull final KeyEvent e )
    {
        System.out.println ( "====== Selected ======" );
        for ( int i = 0; i < list.getModel ().getSize (); i++ )
        {
            if ( list.isCheckBoxSelected ( i ) )
            {
                System.out.println ( "Selected: " + i );
            }
        }
    }
} );
```
And it does seem to output selected indexes correctly at all times.

> It turns out both setCheckBoxSelected and isCheckBoxSelected() don't work well and don't give CONSISTENT results without wrapping them in EDT.

Normally any Swing component setters must be used in EDT anyway as they perform a visual update as a result of changes and it has to be done on EDT. Also all Swing component models are not suited for multi-threaded modifications as they also perform visual updates as a result of changes in most cases, which again - have to be done on EDT.

Accessing any Swing component settings/values is a different topic. You can do that outside of EDT, but you do potentially have a risk of getting a value mid change, but that is rarely a case because of how UI are built and operated. It shouldn't be a problem in case of `WebCheckBoxList` either.

> After I wrap both setCheckBoxSelected and isCheckBoxSelected() in SwingUtilities.invokeLater(), they work well now.

That shouldn't matter because if the `ActionListener` you're using is invoked by some Swing component - it is already on EDT. It is always the case for any listeners implementing `EventListener`.

I tried the bits of code you provided but they do work perfectly fine in either case:
```java
public class CheckBoxListTest
{
    public static void main ( final String[] args )
    {
        SwingTest.run ( new Runnable ()
        {
            @Override
            public void run ()
            {
                final CheckBoxListModel model = new CheckBoxListModel ();
                model.add ( new CheckBoxCellData ( "Sample 1" ) );
                model.add ( new CheckBoxCellData ( "Sample 2" ) );
                model.add ( new CheckBoxCellData ( "Sample 3" ) );

                final WebCheckBoxList list = new WebCheckBoxList ( StyleId.checkboxlist, model );

                list.setCheckBoxSelected ( 0, true );
                list.setCheckBoxSelected ( 1, false );
                list.setCheckBoxSelected ( 2, true );

                final WebButton button = new WebButton ( "Deselect selected ones", new ActionListener ()
                {
                    @Override
                    public void actionPerformed ( final ActionEvent e )
                    {
                        for ( int i = 0; i < list.getModel ().getSize (); i++ )
                        {
                            if ( list.isCheckBoxSelected ( i ) )
                            {
                                list.setCheckBoxSelected ( i, false );
                            }
                        }
                    }
                } );

                TestFrame.show ( false, list, button );
            }
        } );
    }
}
```
There must be something else in your code that affects the result.

**Comment by mgarin** [comment] 2019-12-05 10:20
I'll be moving this to v1.2.12 as I'm currently unable to reproduce the bug.

**Comment by mgarin** [comment] 2019-12-09 10:41
@mokun 
So, does it work consistently for you when calls are wrapped in EDT?

**Comment by mokun** [comment] 2019-12-09 22:11
> So, does it work consistently for you when calls are wrapped in EDT?

Yes. for whatever weird reasons, the ActionListener after wrapping that method with SwingUtilities.invokeLater() in actionPerformed() in that ActionListener, the issue goes away  

So I'll leave it the way it is now :D

**Comment by mgarin** [comment] 2019-12-10 08:18
Ok, I'll be closing this one then.

**Closed by mgarin** 2019-12-10 08:18 UTC
Labels: bug
