### ISSUE TITLE
Menu does not open sometimes

### ISSUE THREAD

**Issue by Sorceror** [mgarin/weblaf#205] opened 2014-11-25 18:12 UTC
I made up-to-date build (commit fe7a322) and use it in our application, but I notice some weird behavior on menu. Menu sometimes does not open. Check the gif screencast for details.
![2014-11-25_18-58-58](https://cloud.githubusercontent.com/assets/944282/5188552/475a7896-74d6-11e4-80ea-8d520c33bde7.gif)

**Comment by Sorceror** [comment] 2015-02-12 11:43
I just tried up-to-date build (commit 5285505) and still same problem. First menu in menu bar is shown only on second click or second mouse over.

![2015-02-12_12-39-56](https://cloud.githubusercontent.com/assets/944282/6166856/af5cfc40-b2b4-11e4-8b12-57b6b1242b61.gif)

**Comment by mgarin** [comment] 2015-02-12 15:23
I am aware of this issue but unfortunately I didn't find its source yet - I tried to apply a few quick changes but they didn't give any results. I will be looking deeper into this and some other issues this and next week and will comment here if I find and fix the source.

**Comment by mgarin** [comment] 2015-03-16 16:28
I have just tried a few test applications with different menus and I weren't able to reproduce this one anymore. Does it still appear with [pre-release v1.29 artifacts](weblookandfeel.com/downloads/prerelease/) for you?

**Comment by Sorceror** [comment] 2015-03-19 21:48
This is fixed now (tested on version based on commit d2fbc288c0c16697705525bc1b5c085586f5148f ) thanks a lot :+1:

**Comment by mgarin** [comment] 2015-03-19 23:57
Awesome!
Probably that was some side-effect of older way of handling the popup window background.
Still, not sure what exactly caused this behavior. And hopefully won't need to know anytime soon :)

**Comment by Sorceror** [comment] 2015-03-20 12:01
OK it's still not working in all cases, but I have to be able to narrow it down.

For some reason (explanation follows), method `showPopup()` in `JPopupMenu` class return Heavyweight instance instead of Lightweight at line `Popup newPopup = getUI().getPopup(this, desiredLocationX, desiredLocationY);`, then followup line `newPopup.show();` calls `show()` method of `Popup` class instead of `show()` in private static inner class `LightWeightPopup` of `PopupFactoryClass`.

The reason why wrong type was selected is hidden inside line `return super.getPopup ( popup, x, y );` in `WebPopupMenuUI` class, which leads to `return popupFactory.getPopup(popup.getInvoker(), popup, x, y);` in `PopupMenuUI` class and then to method `getPopup(...)` in `PopupFactory` class.

There the line `Popup popup = getPopup(owner, contents, x, y, popupType);` returns `null` value and following if with comment `// Didn't fit, force to heavy.` leads to creation of heavy popup `popup = getPopup(owner, contents, x, y, HEAVY_WEIGHT_POPUP);`.

So I followed into the reason why does not fit and get this. Method `getPopup(...)` in `PopupFactory` leads through `case LIGHT_WEIGHT_POPUP` eventually to method `Popup getLightWeightPopup()` in `LightWeightPopup` inner class of `PopupFactory` class. There method `popup.fitsOnScreen()` return `false` instead of `true` (for other correctly working/showing menus).

The reason why it return `false` is hidden inside method `fitsOnScreen()` in `ContainerPopup` inner class of `PopupFactory` class. Condition `JPopupMenu.canPopupOverlapTaskBar()` is evaluated as `true` so line `result = parentBounds.intersection(popupArea).contains(x, y, popupWidth, popupHeight);` sets the value of `result` variable. 
For **correctly shown popup** I'm getting `parentBounds: [x=-1600,y=23,width=1600,height=837]`, `popupArea: [x=-1600,y=0,width=1600,height=860]`, so `[x=-1600,y=23,width=1600,height=837].contains(-1573, 45, 105, 90)` and that is `true`.
For **incorrectly shown popup** I'm getting `parentBounds: [x=-1600,y=23,width=1600,height=837]`, `popupArea: [x=-1600,y=0,width=1600,height=860]`, so `[x=-1600,y=23,width=1600,height=837].contains(-1612, 45, 144, 118)` and that is obviously `false`.

*Could you please look into that? It's currently blocker for me.*

**Comment by mgarin** [comment] 2015-03-20 14:05
Well, I actually have explained why first menu gets into separate window and uses heavyweight popup long ago in this request: #130

Its not a secret and not actually an issue - any menu might get into heavyweight popup if it doesn't fit into frame content bounds, this is simply how it works, even in default Swing - you can try opening frame packed to the state that only menu bar is visible - all menu popups will be heavyweight in that case, otherwise those won't be able to display properly.

The best way to narrow down the actual cause of the issue is to find a small working code example where it can be easily reproduced. Also your JDK and OS versions are important for this case as those might affect menu behavior.

**Comment by Sorceror** [comment] 2015-03-20 16:53
OK, I didn't know that.. Wouldn't be possible to move that popup some way to fit into the rendering space? It happens only in particular circumstances, which I guess I won't be able to replicate. I'll try to make SSCCE, ale I'll let you know..

**Comment by mgarin** [comment] 2015-03-20 18:03
It is possible - just add some margin on the right of the menu bar (like 4 or 6 px) so that first popup menu moves to the right following the menu. I might also include that later into default styling.

Still, I would prefer fixing this issue rather than making a small workaround which is still doesn't save you from all possible cases :) 

So yes, I'll be waiting for an SSCCE or just some working example if you can't find the "compact" case where this issue can be reproduced. In some cases that might be other components affecting menu behavior.

**Comment by Sorceror** [comment] 2015-06-03 18:13
I've try this again with commit 09367c9c1f0d828ed047e932ca28c5230ad79e99 and unfortunately with same result, that first menu does not open every second selection.

Although I was able to create SSCCE and narrow it down to correlation with `notifications`.
Following SSCCE will *create window with some menus in menu bar and instantly opens another dialog* (app login dialog in my real app) *that after popup notification some action* (with success or fail in my real app). *Right after notification is closed* (timeout) *first menu is not shown every other selection*. **This all seems to be true only when the app window is in maximized state.**

```Java
public class MenuSSCCE {
    public MenuSSCCE() {
        WebLookAndFeel.install();

        WebFrame frame = new WebFrame("test");
        frame.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);

        WebMenuBar menuBar = new WebMenuBar();
        WebMenu firstMenu = new WebMenu("t1");
        WebMenuItem testItem = new WebMenuItem("t1 - 1");
        firstMenu.add(testItem);
        testItem = new WebMenuItem("t1 - 2");
        firstMenu.add(testItem);
        WebMenu secondMenu = new WebMenu("t2");
        testItem = new WebMenuItem("t2 - 1");
        secondMenu.add(testItem);
        testItem = new WebMenuItem("t2 - 2");
        secondMenu.add(testItem);
        WebMenu thirdMenu = new WebMenu("t3");
        testItem = new WebMenuItem("t3 - 1");
        thirdMenu.add(testItem);
        menuBar.add(firstMenu);
        menuBar.add(secondMenu);
        menuBar.add(thirdMenu);
        frame.setJMenuBar(menuBar);

        SwingUtilities.invokeLater(() -> {
            TestDialog dlg = new TestDialog(frame);
            dlg.pack();
            dlg.setLocationRelativeTo(frame);
            dlg.setVisible(true);
        });

        frame.setExtendedState(Frame.MAXIMIZED_BOTH);
        frame.setVisible(true);
    }

    private class TestDialog extends WebDialog {
        public TestDialog(JFrame owner) {
            super(owner, true);

            this.add(new WebButton("close", (e) -> {
                NotificationManager.showNotification(owner, "close message").setDisplayTime(2000);
                TestDialog.this.dispose();
            }));
        }
    }

    public static void main(String[] args) {
        new MenuSSCCE();
    }
}
```

Here is GIF screen capture which shows that **menu works correctly until notification close** and **then works only on every second time**. (Sorry I was not able to select lower resolution due to fact it's issue only in maximized state)
![gif recording](http://imageshack.com/a/img538/8601/bgt4kx.gif)

This is pretty bummer for me, if you would find some time to investigate this issue in near future, I would really appreciate that. :+1:

**Comment by mgarin** [comment] 2015-06-04 09:24
Thanks for the detailed example, I was able to reproduce this issue and will find a way to fix it.

Meanwhile - I do not recommend using the last version which is in `master` right now since it has another issue introduced with `09367c9` commit changes. It leads to popup disappearance after the first time it is displayed on some OS. There was a pre-release build with last stable version which is just a few commits behind: http://weblookandfeel.com/downloads/prerelease/

Fix for the current `master` branch issue was already made along with some other changes in `styling` branch. Fix for the first menubar popup will also be made there and then merged into `master` along with other changes.

**Comment by Sorceror** [comment] 2015-06-04 10:07
Thanks, let me know if I can assist you in any way..
The pre-release build is made on what exact commit?

**Comment by mgarin** [comment] 2015-06-04 14:21
This one is the last included in current pre-release build: https://github.com/mgarin/weblaf/commit/25d49178ec1b0b28dd452e4f8160fa89b8f6aedf

Regarding the menubar - I have found the source of the issue (thank to your example with the notification popup!) - instead of creating new windows for popups Swing re-uses old ones which were created for other purposes and were disposed - I guess that was some kind of optimization. WebLaF uses a reflection hack to create and handle heavyweight popups for my its own purposes - like creating notification windows and such. These popup windows are getting re-configured and after disposal they are being re-used by other default Swing popup sources like menus in menubar. This is why the issue appears.

I am not yet sure what settings exactly cause the issue, but it seems it has something to do with window opacity/transparency and focusable state.

**Comment by mgarin** [comment] 2015-06-04 15:12
Here is the real fix for this issue: https://github.com/mgarin/weblaf/commit/e30f269f698afb2d85b3bc047b06367bf63e5edf
Plus it also requires a small fix in `ReflectUtils`: https://github.com/mgarin/weblaf/commit/3f810e689fb43d3ce7fb82efa9d5766d4bfc46d2
I cannot really add it into `master` branch right now, it will only be added with other changes from `styling`, so if you want this fix asap you might want to create a local version with these changes until `styling` branch changes are ready.

**Comment by mgarin** [comment] 2015-06-04 15:14
I will probably add a few fixes into `master` later and these changes as well, but cannot say for sure right now. I really want to focus on finishing the `styling` part right now.

**Comment by Sorceror** [comment] 2015-06-05 09:33
I made custom build based on commit 25d4917 and cherry picked the fixes and I can confirm this issue seems to be solved for good :+1: .
Thanks a lot for such a quick response!

**Comment by mgarin** [comment] 2015-06-05 11:11
I am pretty sure now that this bug shouldn't appear anymore :)

Also I found out a few interesting things in Swing while digging into this issue. Like that popup recycling "feature" which most likely was some kind of performance improvement.

Anyway, I'll be closing this issue as soon as the changes are in the `master` branch.

**Closed** 2016-05-13 14:30 UTC
Labels: bug, confirmed, solved
