### ISSUE TITLE
DefaultTreeCellRenderer

### ISSUE THREAD

**Issue by RobertBColton** [mgarin/weblaf#341] opened 2015-11-11 10:19 UTC
I use this code to remove leaf icons for a tree in my preferences panel.
```Java
DefaultTreeCellRenderer renderer = (DefaultTreeCellRenderer) tree.getCellRenderer();
renderer.setLeafIcon(null);
renderer.setClosedIcon(null);
renderer.setOpenIcon(null);
```
Which results in the following exception.
```
java.lang.ClassCastException: com.alee.laf.tree.WebTreeCellRenderer cannot be cast to javax.swing.tree.DefaultTreeCellRenderer
	at org.lateralgm.subframes.GameSettingFrame.<init>(GameSettingFrame.java:795)
	at org.lateralgm.subframes.GameSettingFrame.<init>(GameSettingFrame.java:760)
	at org.lateralgm.main.LGM.main(LGM.java:2286)
```
This works under GTK, Windows L&F, all of the Synthetica and other look and feels.

**Comment by mgarin** [comment] 2015-11-11 10:29
WebLaF tree doesn't use Swing `DefaultTreeCellRenderer` by default - instead it uses its own renderer - `WebTreeCellRenderer`. You can cast your renderer to `WebTreeCellRenderer` and call those three methods as they are also available within `WebTreeCellRenderer`:
```java
WebTreeCellRenderer renderer = ( WebTreeCellRenderer ) tree.getCellRenderer ();
renderer.setRootIcon ( null );
renderer.setLeafIcon ( null );
renderer.setClosedIcon ( null );
renderer.setOpenIcon ( null );
```
I have also added `setRootIcon` there as it is provided separately in `WebTreeCellRenderer`.

**Comment by mgarin** [comment] 2015-11-11 16:55
Does this solve you problem? :)

**Comment by RobertBColton** [comment] 2015-11-11 17:19
That does yes, and so does creating a whole new renderer. But, the other way does not fail with any other look and feel.

**Comment by mgarin** [comment] 2015-11-11 17:29
Casting renderer to something specific like `DefaultTreeCellRenderer` should generally be fine, but nothing really says that it can't be replaced in L&F. It can be and there are even methods opened for that in the tree UI.

Usually if you want to replace those icons you would modify UI defaults.
Here is how those default icons are usually read by renderers:
```java
        if (!inited || (getLeafIcon() instanceof UIResource)) {
            setLeafIcon(DefaultLookup.getIcon(this, ui, "Tree.leafIcon"));
        }
        if (!inited || (getClosedIcon() instanceof UIResource)) {
            setClosedIcon(DefaultLookup.getIcon(this, ui, "Tree.closedIcon"));
        }
        if (!inited || (getOpenIcon() instanceof UIManager)) {
            setOpenIcon(DefaultLookup.getIcon(this, ui, "Tree.openIcon"));
        }
```
You can put your own icons there through `UIManager.put ( ... )` method call.

Though WebLaF doesn't use a lot of UI defaults (including these) and will go even further in that direction with the next update. The point of this difference as that I can offer a lot more customization if I am not chained by the defaults.

So in general the best way to remove those icons from renderer - simply cast that renderer to `JLabel` and set its icon to `null` since (as I understand) you are trying to remove all icons from the tree elements. But you will need to do that inside the `getTreeCellRendererComponent` which is called on each render. Usually you will need to override this method anyway to provide your own text for each node, unless you are working with some plain data.

**Comment by RobertBColton** [comment] 2015-11-11 19:06
Ah, yeah, that is a good solution as well. I will be changing it anyway so that it will be compatible with Web LaF, it is really very difficult to make Swing application's consistent with all look and feels. So I generally agree with your comments about the poor architecture of Swing, many Java developers do, I mean it's literally even mentioned in some of the Metal comments. This is why JavaFX is quickly becoming the defacto replacement, code is a lot cleaner.

I recently attempted making a small derivative look and feel of Metal as well. I was thinking about doing a real one with a CSS parser and throwing out all of the UI defaults as well. Just make a default style based off of JavaFX's. But it's a substantial amount of work at this point when people are already switching to JavaFX.

Anyway, I'll leave it up to you to close this ticket. At the very least the inconsistency is now documented and people have a reference point of how to solve it.

**Comment by mgarin** [comment] 2015-11-11 23:58
Just another note on that case - why I am not using default Swing renderer specifically - I will be using WebStyledLabel instead of JLabel in the next update for ALL renderers in trees, tables and lists. It gives far better options to style text itself without impacting the performance of the UI. And since the default renderer is a JLabel in its core there is simply no way to use it.

On the styling part and CSS - yes, it is a huge amount of work to do to make it actually work and allow you to style stuff the way you want it to look, like in HTML & CSS which had a looong looong way of good/bad design decisions (and it is still have issues even now).

Java FX is certainly a fresh approach to the UI in Java there, and it is clean in the code and doesn't have a lot of old ugly issues like Swing has. But it also has its downsides and flaws. To be honest - choosing between Swing and Java FX right now I would still prefer Swing even with all its ugly stuff and workarounds for a several reasons. Those reasons will fade away with time and I will certainly be switching to some more Java FX -related stuff later on, but right now I am going to wait with that.

And yes, I'll be closing this ticket now :)

**Closed by mgarin** 2015-11-11 23:58 UTC
Labels: question

**Comment by RobertBColton** [comment] 2015-11-12 00:03
Right, exactly. I always get super excited with the shiny new JavaFX and then realize something's not in there, hence DockFX, a docking framework I came up with over on my account. It needs time.

What bothers me the most though is that the whole .NET/C# scene came after Swing, and nearly a decade later, Windows Forms is still more complete and less buggy than Swing. It's not even so much that Swing is fundamentally broken, it just won't be fixed.

**Comment by mgarin** [comment] 2015-11-12 00:08
Swing isn't really broken, it just has a few arguable designs in it which make your life harder when you try to create your application UI. On the other hand - some concepts are awesome and work perfectly fine. So it isn't that bad. If it was that bad I wouldn't bother creating and supporting a huge L&F library specifically for it that would take years to shape up ;)

**Comment by RobertBColton** [comment] 2015-11-12 00:09
Either way you are doing a great job having it open source and all. It's on the level of quality of Synthetica and those other proprietary look and feels, and it's great that you include a free version for open source as well.

**Comment by Sciss** [comment] 2015-11-12 08:16
+1 from me. I think you are doing an amazing work with WebLookAndFeel, it looks better than a loot of GUI frameworks, not just for Java. Once you get behind the shininess of JavaFX, there is also not that many compelling reasons to prefer it over Swing. It is only gradually becoming available on open source platforms (OpenJFX), and there are still many legacy systems running for which it is not an option. Swing while being a bit rusty has worked fine for a long long time, many libraries are based on it, many people have invested a lot of energy in it that will be vaporised if they had to reimplement everything on top of JavaFX. Also, personally, I'm much more a fan of dynamically and programmatically created GUIs, so the XML stuff in JavaFX is really not anything compelling. And again, putting the reactive part into it is also only nice on the surface, but doesn't help at all if you need to bridge it again with other competing reactive systems and other JVM languages. So if you evaluate all those things, JavaFX doesn't bring that much benefit. It doesn't do anything revolutionary except add CSS. It would be revolutionary if it changed the threading model, for example if it was fully concurrent.

**Comment by mgarin** [comment] 2015-11-12 09:11
@Sciss Even the CSS there is far from perfect if you have tried using it already. One of my colleague who mostly work with HTML/CSS/JS (and with Java/Swing sometimes) called it a living nightmare when he tried creating small app using Java FX. Some things are not working or just work differently.

**Comment by RobertBColton** [comment] 2015-11-12 10:18
I agree basically with all of that. I too found the CSS a tad confusing at first, it's nothing like HTML, I would say Qt's is a little more straight forward. That said, it's no where near as bad as XAML, have either of you worked with WPF before? I love native Windows Forms, but WPF is a nightmare.

I think why some people, including myself, do like JavaFX is because it learns from a few of the mistakes of Swing. It doesn't learn from everything, but it certainly has been thought out a lot more. Where as Swing went through a lot more evolutionary changes, one of the major ones being type safety. JavaFX is a lot closer to the Qt Quick platform, where as Swing is closer to traditional Qt Framework. I just think that because we have something new like JavaFX doesn't mean we need to completely abandon Swing, or that it can't still be improved. One of the problems there is modularity, Oracle is so afraid to break things because every Java SE uses the exact same Swing. With Qt and such, they aren't as afraid to make breaking changes.

**Comment by mgarin** [comment] 2015-11-12 10:31
Breaking things might be good and might be bad, depending on how often you do that and what is the reason for the introduced API break. In case with Swing I actually think it is a good thing they kept API intact even though it forced them to have some nasty workarounds for some things. It is a good thing because it gave a lot of time to developers to learn how to use Swing pretty well and produce a lot of custom awesome extensions for it which don't need super-frequent updates for each JDK update released.

**Comment by RobertBColton** [comment] 2015-11-12 10:49
@mgarin Also Web L&F does a much better job than many of the built in look and feels, I would consider 1.29 already a replacement for the GTK look and feel entirely. And the best part is you don't throw a watermark on the free version like the Synthetica ones, which aren't really even better anyway, it really makes the difference.

**Comment by mgarin** [comment] 2015-11-12 11:03
Adding any watermarks will just render free version useless for a lot of projects. And it will just basically be ugly. This isn't really a big niche anyway so everyone more or less competent will know which L&F is used in the specific application :)

Also on the next updates I was thinking of reproducing some of the native L&F based on the technology provided by WebLaF - this might be really useful for Mac / Linux users specifically. And I will need that for some our internal projects as well if it will be thing.
