### ISSUE TITLE
Event thread deadlock

### ISSUE THREAD

**Issue by behnischJPK** [mgarin/weblaf#488] opened 2018-06-21 12:49 UTC
Hello,
I managed to run into an event-thread deadlock, see the attached threaddump. I removed all unrelated threads, but if you need more information let me know.

This does not seem to happen often, it happened now by having a lot of active jvm threads and by putting some additional load on the cpu.

We are currently using a custom weblaf version, based on the latest master commit  d0e9fd4ede plus some cherry-picks from the styling branch and some extra patches for the file filter selection.

**Comment by behnischJPK** [comment] 2018-06-21 12:51
[threaddump.txt](https://github.com/mgarin/weblaf/files/2123635/threaddump.txt)

**Comment by mgarin** [comment] 2018-06-21 18:08
There surely quite a few EDT deadlocks i've fixed in the `styling` branch code compared to the `master` branch code, but I don't think I'll be able to find and point those out now because of millions of other small changes.

My best guess, after looking at the thread dump you provided (thanks for that one!), is that either older `WebTimer` code ( [master](https://github.com/mgarin/weblaf/blob/master/modules/core/src/com/alee/utils/swing/WebTimer.java) vs [styling](https://github.com/mgarin/weblaf/blob/styling/modules/core/src/com/alee/utils/swing/WebTimer.java) ), one of utilities it uses or one of the specific component implementations that appear in the thread dump have some issues with locks and EDT usage, but it is really hard to tell what exactly causes deadlocks.

In `master` branch code there are quite a few animation threads that are spread across components and are not properly controlled anyhow. I've replaced those with a proper `AnimationManager` and `Transition`s usage in the `styling` branch, for example you can check [MovingHighlightBackground.java](https://github.com/mgarin/weblaf/blob/styling/modules/ui/src/com/alee/painter/decoration/background/MovingHighlightBackground.java) class to see how progress background is now being animated. And Checkbox animation, for instance, have been completely removed since then. 

The problem is - I doubt you can safely move those changes over to the old code as they involve hundreds of other changes and adjustments and use a lot of new major features introduced in `styling` branch code.

Also the fact that you have a custom version of the library code complicates things even further, so I'm not really sure how can I solve this problem.

**Comment by behnischJPK** [comment] 2018-06-22 12:06
Thank you for your detailed comment on this issue. If this part of the code is completely reworked on the styling branch then I agree that there is a good chance that the issue is fixed.

We would be happy to switch to the styling branch. As far as I remember we had the problem that the breadcrumbs could not be styled to match our theme last time we tried the styling branch. Is this possible now? And more generally, would you recommend to switch to the styling branch already?

**Comment by mgarin** [comment] 2018-07-02 08:19
Just a small followup (since the week gone past) - I've looked into the breadcrumbs and got a few ideas about how to bring them live quite soon, so I will do that along with a few other components. It might be a simplified version of what I planned to do with breadcrumbs, but it should still retain all of the original functionality plus incorporated styling.

**Comment by behnischJPK** [comment] 2018-07-02 08:55
Thanks for the information! We are looking forward to try it out .

A simplified version really is sufficient for us now, we would just need a way to set the color and to style them to look a little less button like, but nothing fancy.

**Comment by mgarin** [comment] 2018-07-10 00:10
An update on the `WebBreadcrumb` component - I've been working on it last week and got quite close to completion, I managed to overcome most challenges, but there is still one more thing I need to implement to make `WebBreadcrumb` function properly.

It's styling is already fully-functional and has two basic options:

![image](https://user-images.githubusercontent.com/2361389/42457367-fda56e54-839f-11e8-83f8-89d82e06d609.png)

![image](https://user-images.githubusercontent.com/2361389/42458946-89433394-83a3-11e8-9584-0f8c4260d100.png)

(this is just a small demo app I use for debugging breadcrumbs)

As you can see on the screenshot - variant with panels still has issues with padding. Other components might seem to be fine, but in reality they use a few small hacks to fix padding problems, so even those are still not in the state I would like to push out.

So the last thing I need is padding (and probably margin) support for component decoration states. Right now padding and margin are only available on component/ui level. All component decorations and their states are managed by painters, but those painters have no access to component padding and margin which is quite limiting. `WebBreadcrumb` directly suffers from the lack of that feature.

It won't be too hard to add and it will actually allow me to adjust a lot of styles and fix a few other general issues, but I need to make sure that it won't break anything as it is quite a critical change. As soon as that part is done - I will push all changes together with new `WebBreadcrumb`, I should be able to finish it this week.

**Comment by ohle** [comment] 2018-07-10 07:41
That's great news! That will probably allow us to switch to the styling branch soon — thanks for the update.

**Comment by mgarin** [comment] 2018-07-20 18:49
I have pushed revamped `WebBreadcrumb` component and a bunch of related changes: https://github.com/mgarin/weblaf/commit/f04999e3378be018969cf31825e1ab2cca0d8122

It is fully functioning, but I didn't manage to add extra paddings/margins into the current styling scheme behavior, so I left a few minor workarounds in place in the `breadcrumb` styles. I will push padding and margin improvements slightly later, separately from everything else, instead of delaying the component release.

You can check out the new demo section for `WebBreadcrumb` in the demo application:

![image](https://user-images.githubusercontent.com/2361389/43019522-f76116dc-8c65-11e8-9beb-fed5bcb8d362.png)

Quite a few things changed for `WebBreadcrumb` implementation and API:

- There are no custom elements like `WebBreadcrumbButton` or `WebBreadcrumbPanel` anymore. You can simply use components like `JPanel` or `WebButton` directly. This change was made mainly to simplify breadcrumb usage and to avoid any kinds of component-level workarounds. That approach also makes it much easier to add support for more breadcrumb components (you can add your own ones as well if needed).

- Whenever you add a component directly on the `WebBreadcrumb` - that component will automatically be re-styled to look like breadcrumb element IF that feature is enabled, added component is supported and it doesn't already use a `Painter` that implements `BreadcrumbElementPainter`. That feature can be disabled, but in that case you will need to manually specify `StyleId` for the added elements which is not a bit deal, but probably won't be needed in most cases.

- `BreadcrumbLayout` has a `Strategy` option that allows you to choose from one of four layouting strategy types: keep each element at preferred width, force all elements to have same width (equal to maximum width element), force last element to always fill remaining space, force all elements to have same width (equal to `1/element count` of total breadcrumb width.

- Breadcrumb overall performance have been improved. Visual updates are not queued for all breadcrumb elements anymore, only to elements that were actually affected by the changes (whatever it is - addition or removal of an element, breadcrumb settings changes, size changes etc).

This is not all though, breadcrumb now supports a big set of components that can be added directly on it and re-styled to fit breadcrumb elements style:

- `JPanel` and `WebPanel`
- `JLabel` and `WebLabel`
- `WebStyledLabel`
- `WebLink`
- `JButton` and `WebButton`
- `JToggleButton` and `WebToggleButton`
- `WebSplitButton`
- `JComboBox` and `WebComboBox`
- `WebDateField`
- `JCheckBox` and `WebCheckBox`
- `WebTristateCheckbox`
- `JRadioButton` and `WebRadioButon`
- `JTextField` and `WebTextField`
- `JFormattedTextField` and `WebFormattedTextField`
- `JPasswordField` and `WebPasswordField`

I might add more components support in future, especially considering that it barely takes any effort now, but even the current set should be more than enough to start working with it right now :)

Also, there is no direct API for providing support for any other/custom components within `WebBreadcrumb`, but if something important or highly requested is missing I will be adding it along the way. API for adding support for custom elements might become available later if it will actually be needed, but it might end up not being needed at all considering that almost all elements that make sense in context of the breadcrumb are already supported.

**Comment by mgarin** [comment] 2018-07-20 18:51
I will close this issue as `WebBreadcrumb` should now be available and this issue topic kinda derailed from the original one :)

If you will have any problems with `WebBreadcrumb` - probably make a new topic for an easier/clear conversation, but if you will get deadlocks on the newer `styling` branch version - feel free to reopen this one.

**Closed by mgarin** 2018-07-20 18:51 UTC
Labels: bug
