### ISSUE TITLE
How to change WebButton Background from the code

### ISSUE THREAD

**Issue by Mark-Shorcan** [mgarin/weblaf#524] opened 2019-08-21 19:13 UTC
Hi,

I am trying to upgrade to weblaf1.2.9, I love it so far but I run into few problems.
I am trying to change the webbutton background dynamically, before i can just call the setbackgoud(), but now  I found that does not work anymore, I can only set  the backgound in the skin xml.
Is there a way I can do it in the old way? I do not want to create a xml for each color I use.

**Comment by mgarin** [comment] 2019-08-23 12:04
This is a good question, there is indeed no easy solution for the case. I did not want to create any workarounds for the styling system and wanted to make it strict this time around. So if you want to change any visual part of any component - you will need to interact with styles in one or another way.

Here is the correct solution I can suggest for your particular case:
1. Make a custom `Background` implementation that uses component's background color
2. Use it withing your button style instead of the default background
3. Use your custom style for any button that you want to use background color instead of default colors

Since the question about background is pretty common - I've added `ComponentBackground` implementation in the library and committed it recently: https://github.com/mgarin/weblaf/commit/419725e33677ecc3251cccb2de1a44a5da818dc6

It will be available in the v1.2.10 update, but until then you can just copy-paste it's code:
```java
@XStreamAlias ( "ComponentBackground" )
public class ComponentBackground<C extends JComponent, D extends IDecoration<C, D>, I extends ComponentBackground<C, D, I>>
        extends AbstractBackground<C, D, I>
{
    @Override
    public void paint ( final Graphics2D g2d, final Rectangle bounds, final C c, final D d, final Shape shape )
    {
        final float opacity = getOpacity ();
        if ( opacity > 0 )
        {
            final Composite oc = GraphicsUtils.setupAlphaComposite ( g2d, opacity, opacity < 1f );
            final Paint op = GraphicsUtils.setupPaint ( g2d, c.getBackground () );
            g2d.fill ( shape );
            GraphicsUtils.restorePaint ( g2d, op );
            GraphicsUtils.restoreComposite ( g2d, oc, opacity < 1f );
        }
    }
}
```
to your project if you need it now. 
And don't forget to call:
```java
XmlUtils.processAnnotations ( ComponentBackground.class );
```
to make it usable in XML.

Regarding the style for the button - it's pretty simple:
```xml
    <style type="button" id="color">
        <painter>
            <decorations>
                <decoration>
                    <ComponentBackground />
                </decoration>
            </decorations>
        </painter>
    </style>
```
In case you want your color to be present on all states - simply add it to those states as well:
```xml
    <style type="button" id="color">
        <painter>
            <decorations>
                <decoration>
                    <ComponentBackground />
                </decoration>
                <decoration states="pressed">
                    <ComponentBackground />
                </decoration>
                <decoration states="disabled">
                    <ComponentBackground />
                </decoration>
            </decorations>
        </painter>
    </style>
```
Although I wouldn't recommend that since pressed/disabled states will not be as emphasized in that case. Although you can always create your own solution for that if you have any ideas.

Once you have this style in the skin or extension you're using for your app - you can use it in code:
```java
public final class ColoredButton
{
    public static void main ( final String[] args )
    {
        SwingUtilities.invokeLater ( new Runnable ()
        {
            @Override
            public void run ()
            {
                WebLookAndFeel.install ( MySkin.class );
                TestFrame.show (
                        25, false, 25,
                        new WebButton ( "Default" ),
                        new WebButton ( StyleId.of ( "color" ), "Colored default" ),
                        new WebButton ( StyleId.of ( "color" ), "Colored red" )
                        {
                            {
                                setBackground ( Color.RED );
                            }
                        },
                        new WebButton ( StyleId.of ( "color" ), "Colored blue" )
                        {
                            {
                                setBackground ( Color.BLUE );
                            }
                        }
                );
            }
        } );
    }
}
```

Result is not really appealing since I didn't pick any decent colors, but it works as intended:
![image](https://user-images.githubusercontent.com/2361389/63590955-1a736280-c5b6-11e9-87c7-3dca2d1d853d.png)

Now you can simply use `StyleId.of ( "color" )` for any of your buttons to make them "colorable". Similar approach can also be applied to any other component or piece of UI in general.

There will be another approach available through the skin variables ( #460 ) that are planned for v1.3.0 update. It will allow you to overwrite some of the style settings in runtime making it possible to modify the style without touching it directly. Although there will also be some limitations and it is not yet in work, so I wouldn't expect these changes to be available soon.

**Comment by mgarin** [comment] 2019-08-23 12:15
And just a side note - I do not have any plans to make any methods for direct style adjustments like there were before. The main reason is - all styles are fully customizable and there could be no unified API to change button background, border colors or anything like that - they might simply not be in the style at all in the first place or there might be multiple borders or backgrounds used.

That being said, I do plan on providing better accessibility for some of the style-related stuff like skin variables ( #460 ) and I also do plan to allow creating styles from the code instead of XML ( #427 ) which should help a lot with solving cases like this one.

**Comment by mgarin** [comment] 2019-08-26 10:32
I'll be closing this issue since the question should be answered, but feel free to reopen it if you still have problems with the offered solution!

**Closed by mgarin** 2019-08-26 10:32 UTC
Labels: question

**Comment by wyj3531** [comment] 2021-09-14 06:34
i use you the mothod you suggest dont work.
gust want to set button text color and button bg color. how to do .
`  WebButton btnOk= new WebButton ( StyleId.of ( "btnOk" ), "确定" )
        {
            {
                setBackground ( Color.RED );
            }
        };`

`   <style type="button" id="mybutton" padding="2,4,2,4">
        <painter>
            <decorations>
                <decoration>
                    <ComponentBackground />
                </decoration>
                <decoration states="pressed">
                    <ComponentBackground />
                </decoration>
                <decoration states="disabled">
                    <ComponentBackground />
                </decoration>
            </decorations>
        </painter>
    </style>`

**Comment by mgarin** [comment] 2021-09-14 11:06
You have incorrect style identifier in the example you've shown, this is the one you need - `StyleId.of ( "mybutton" )`
Otherwise this should work.
