### ISSUE TITLE
Problems using WebLaf components using WYSIWYG from the netbeans IDE

### ISSUE THREAD

**Issue by Kaly380** [mgarin/weblaf#635] opened 2020-07-26 16:57 UTC
When trying to leave the component of the palette I get the following message

![image](https://user-images.githubusercontent.com/6775078/88484801-19218700-cf37-11ea-9908-ef0b7d43eefa.png)

![image](https://user-images.githubusercontent.com/6775078/88484810-29396680-cf37-11ea-9f30-1fa3195b1c1c.png)

How can I use the components using WYSIWYG from the netbeans IDE

I hope your support thanks

**Comment by mgarin** [comment] 2020-07-27 10:27
This is a known problem with NetBeans and potentially any other WYSIWYG editor. WebLaF requires initialization of it's static managers to work properly which occurs when L&F is installed. WYSIWYG editors do not properly install L&F which leads to the issue you're seeing. And, as far as I know, there is no good way to fix that on the WYSIWYG editor side.

I'll close this issue since it's a duplicate of the older one: #18 - you can follow it instead to see when it will be implemented.

Although I will be honest - it's pretty low on my priority list for two reasons:
- Implementing this might take a lot of time and cause issues for other WebLaF users in some specific cases
- I'm not a fan of WYSIWYG editors for Swing and always advocate for pure UI coding for multiple reasons

**Closed by mgarin** 2020-07-27 10:27 UTC
Labels: NetBeans, confirmed, enhancement
