### ISSUE TITLE
Unknown component UI on startup

### ISSUE THREAD

**Issue by Mark-Shorcan** [mgarin/weblaf#513] opened 2019-07-18 13:39 UTC
I am using webLaf 1.27 with win10 and Java8
On startup of my app I see this occasionally, which will cause all the webPanel unresponsive.
Can you help me with this please :D

```
com.alee.managers.style.StyleException: Unknown component UI class ID: PanelUI
    at com.alee.managers.style.skin.WebLafSkin.getSupportedComponentTypeImpl(WebLafSkin.java:132)
    at com.alee.managers.style.skin.WebLafSkin.applySkin(WebLafSkin.java:209)
    at com.alee.managers.style.skin.WebLafSkin.applySkin(WebLafSkin.java:192)
    at com.alee.managers.style.StyleManager.applySkin(StyleManager.java:345)
    at com.alee.managers.style.StyleManager.applySkin(StyleManager.java:325)
    at com.alee.laf.panel.WebPanelUI.installUI(WebPanelUI.java:106)
    at javax.swing.JComponent.setUI(JComponent.java:666)
    at javax.swing.JPanel.setUI(JPanel.java:153)
    at com.alee.laf.panel.WebPanel.updateUI(WebPanel.java:901)
    at javax.swing.JPanel.<init>(JPanel.java:86)
    at javax.swing.JPanel.<init>(JPanel.java:95)
    at com.alee.laf.panel.WebPanel.<init>(WebPanel.java:54)
    at com.shorcan.dx.client.trader.auction.notification.AuctionNotificationPanel.initPanelAndPainter(AuctionNotificationPanel.java:171)
```

**Comment by Mark-Shorcan** [comment] 2019-07-18 13:46
Got the same exception  for WebLabel  and WebScrollBar as well, am i doing sth wrong?

```
com.alee.managers.style.StyleException: Unknown component UI class ID: LabelUI
	at com.alee.managers.style.skin.WebLafSkin.getSupportedComponentTypeImpl(WebLafSkin.java:132)
	at com.alee.managers.style.skin.WebLafSkin.applySkin(WebLafSkin.java:209)
	at com.alee.managers.style.skin.WebLafSkin.applySkin(WebLafSkin.java:192)
	at com.alee.managers.style.StyleManager.applySkin(StyleManager.java:345)
	at com.alee.managers.style.StyleManager.applySkin(StyleManager.java:325)
	at com.alee.laf.label.WebLabelUI.installUI(WebLabelUI.java:96)
	at javax.swing.JComponent.setUI(JComponent.java:666)
	at javax.swing.JLabel.setUI(JLabel.java:261)
	at com.alee.laf.label.WebLabel.updateUI(WebLabel.java:241)
	at javax.swing.JLabel.<init>(JLabel.java:164)
	at javax.swing.JLabel.<init>(JLabel.java:235)
	at com.alee.laf.label.WebLabel.<init>(WebLabel.java:50)
```

```com.alee.managers.style.StyleException: Unknown component UI class ID: ScrollBarUI
	at com.alee.managers.style.skin.WebLafSkin.getSupportedComponentTypeImpl(WebLafSkin.java:132)
	at com.alee.managers.style.skin.WebLafSkin.applySkin(WebLafSkin.java:209)
	at com.alee.managers.style.skin.WebLafSkin.applySkin(WebLafSkin.java:192)
	at com.alee.managers.style.StyleManager.applySkin(StyleManager.java:345)
	at com.alee.managers.style.StyleManager.applySkin(StyleManager.java:325)
	at com.alee.laf.scroll.WebScrollBarUI.setStyleId(WebScrollBarUI.java:150)
	at com.alee.utils.LafUtils.setScrollBarStyleId(LafUtils.java:153)
	at com.alee.laf.scroll.WebScrollPaneUI.installUI(WebScrollPaneUI.java:102)
	at javax.swing.JComponent.setUI(JComponent.java:666)
	at javax.swing.JScrollPane.setUI(JScrollPane.java:380)
	at com.alee.laf.scroll.WebScrollPane.updateUI(WebScrollPane.java:234)
	at javax.swing.JScrollPane.<init>(JScrollPane.java:305)
	at javax.swing.JScrollPane.<init>(JScrollPane.java:323)
	at com.alee.laf.scroll.WebScrollPane.<init>(WebScrollPane.java:50)
	at com.alee.laf.scroll.WebScrollPane.<init>(WebScrollPane.java:45)
	at com.alee.laf.scroll.WebScrollPane.<init>(WebScrollPane.java:40)
````

**Comment by mgarin** [comment] 2019-07-18 14:04
I'm not really sure what exactly caused issues you are seeing - it might be newer JDK version (older releases were mostly tested on JDK6 and JDK7 at most) or some specific problem that happens due to the way you use L&F in your application.

Exceptions you posted only point out that for some reason UI class mapping failed to initialize, but the real exception is hidden within the `StyleManager`.

Generally speaking - 1.27 and 1.28 versions are quite outdated and contain a lot of issues that have been fixed since. That being said the upcoming 1.2.9 (former 1.29) update is still in works but will be released at the end of this month and strongly recommend trying it instead of the older releases. Once it is properly released - it will also be available here and on the site.

You can find snapshot versions of 1.2.9 here:
https://oss.sonatype.org/content/repositories/snapshots/com/weblookandfeel/

Or you can attach it to your maven project (if you are using one):
```xml
    <dependencies>
        <dependency>
            <groupId>com.weblookandfeel</groupId>
            <artifactId>weblaf-demo</artifactId>
            <version>1.2.9-SNAPSHOT</version>
        </dependency>
    </dependencies>

    <repositories>
        <repository>
            <id>sonatype-snapshot-rep</id>
            <name>Sonatype snapshot repository</name>
            <url>https://oss.sonatype.org/content/repositories/snapshots</url>
            <layout>default</layout>
            <releases>
                <enabled>true</enabled>
                <updatePolicy>never</updatePolicy>
            </releases>
            <snapshots>
                <enabled>true</enabled>
                <updatePolicy>never</updatePolicy>
            </snapshots>
        </repository>
    </repositories>
```

If the problem you're currently seeing appears on the snapshot version as well - I will need some [SSCCE](http://sscce.org/) that displays the issue so I can reproduce it locally and fix it.

**Comment by Mark-Shorcan** [comment] 2019-07-18 14:40
Thx! i will try the 1.29

**Comment by mgarin** [comment] 2019-07-29 08:28
Did newer version help?

**Comment by mgarin** [comment] 2019-07-31 17:50
I'll close this for now, but feel free to reopen if you're still encountering the same issue on newer version.

**Closed by mgarin** 2019-07-31 17:50 UTC
Labels: bug
