### ISSUE TITLE
WebDynamicMenu background window size does not accommodate menu item tool-tips

### ISSUE THREAD

**Issue by FrizzyCode** [mgarin/weblaf#609] opened 2020-03-07 02:51 UTC
When attaching tool-tips to a WebDynamicMenuItem, in most configurations the tool-tip is cut off due to the transparent background window not leaving enough space on the sides of the menu. Is there a way I can circumvent this? I've tried setting the margin and padding to larger values, which has had no effect.

**Comment by mgarin** [comment] 2020-03-08 00:42
Which tooltips are you using though?
Custom WebLaF ones?

**Comment by FrizzyCode** [comment] 2020-03-08 00:50
> Which tooltips are you using though?
> Custom WebLaF ones?

I am assigning tooltips to the DynamicMenuItems via The TooltipManager provided by WebLAF.

**Comment by mgarin** [comment] 2020-03-09 18:38
Custom tooltips are currently limited in space to the bounds of glass pane of the window they're displayed on. In case of `WebDynamicMenu` - that is the transparent rectangle of the undecorated window on which menu elements are positioned.

I do want to add some improvements for custom tooltips (#63) but there are a few issues, including JDK bugs, that stop me from doing that. So my general recommendation for now is to use basic Swing tooltips in cases like this one - those can be properly displayed outside of parent's window bounds due to being simple rectangular popups.

**Comment by mgarin** [comment] 2020-03-09 18:38
I'll close this issue as it is basically a duplicate of #63.

**Closed by mgarin** 2020-03-09 18:38 UTC
Labels: bug
