### ISSUE TITLE
Weblaf L&F and Netbeans Pallete

### ISSUE THREAD

**Issue by Almaz-KG** [mgarin/weblaf#270] opened 2015-04-22 13:31 UTC
Hi everybody!

I trying to use some weblaf components in my project, and I have one problem with integration L&F with NetBeans Form Designer (GUI Builder)
My question is: How to add to netbeans palette weblaf controls?

I try resolve this problem by this article http://wiki.netbeans.org/FaqFormUsingCustomComponent , but I get error 

```
java.lang.RuntimeException: Unable to find LanguageUpdater for component: com.alee.laf.button.WebButton[,0,0,0x0,invalid,alignmentX=0.0,alignmentY=0.5,border=com.alee.utils.laf.WeblafBorder@6da50a03,flags=16777504,maximumSize=,minimumSize=,preferredSize=,defaultIcon=jar:file:/F:/Projects/GitHub/IntegrationAutoInstaller/libs/weblaf-complete-1.28.jar!/com/alee/laf/filechooser/icons/backward.png,disabledIcon=,disabledSelectedIcon=,margin=null,paintBorder=false,paintFocus=false,pressedIcon=,rolloverEnabled=false,rolloverIcon=,rolloverSelectedIcon=,selectedIcon=,text=,defaultCapable=true]
	at com.alee.managers.language.LanguageManager.getLanguageUpdater(LanguageManager.java:775)
```

**Comment by mgarin** [comment] 2015-05-05 09:57
The main problem with NetBeans UI editor is that it tries to use components straight ahead and with Web-components it isn't possible in some cases. WebLaF requires various static managers initialization to function properly and that cannot be done in the editor.

I might be able to perform some checks and initialization from the components, but that will require some changes. I will add this enhancement in v1.30 update: #18

**Comment by iamchathu** [comment] 2015-05-12 10:08
Quick Fix

After adding WebComponents to pallets, remove weblaf-ui-1.x.x.jar from Libraries in project window. And Add Weblaf-complete.1.x.x.jar

**Comment by mgarin** [comment] 2015-05-12 11:06
Well, I wrote the first answer considering you didn't have any issues with classpath there, but it seems I was wrong. You have to always use `-complete` JAR for the palette, otherwise you will simply have missing resources/dependencies. 

In the exception you have provided in first post `LanguageUpdater` was missing for `WebButton` component because it is located in `-core` jar.

**Comment by iamchathu** [comment] 2015-05-12 11:59
Yes The problem is when you try to import -complete JAR you'll end up with many components in Palette.

So import -complete JAR and Select only the components you need for the Palette the you are good to go with Netbeans GUI designer.

**Comment by iamchathu** [comment] 2015-06-09 10:12
It's seems that my method wont fix WebCalander, WebFileDrop components :sob:

**Comment by mgarin** [comment] 2016-07-02 13:26
Language exception occurs because of the way components are dependant on managers initialization. Pretty much WebLaF managers should be initialized before you create any component, otherwise you will might get a set of exceptions. 

This will be fixed soon along with some other initialization improvements. 

I'll close this issue to keep a single one related to NetBeans: #18

**Closed by mgarin** 2016-07-02 13:26 UTC
Labels: confirmed, enhancement, NetBeans
