### ISSUE TITLE
Radiobuttons are not always selected when working with models

### ISSUE THREAD

**Issue by iMichka** [mgarin/weblaf#402] opened 2016-07-25 15:05 UTC
If I create separate button models, and separate radiobuttons / checkboxes, only the first one is selected at start. The same code behaves correctly without WebLaf.

This has been tested with the latest commit on the styling branch (d978017e5d958a04b6eecc53ae8bda9498db9a34), with openjdk 8u72-b15-1~precise1 (on ubuntu precise).

```
import com.alee.laf.WebLookAndFeel;

import javax.swing.*;
import java.awt.*;

public class Test extends JFrame {

    private Test() {
        initUI();
    }

    private void initUI() {

        WebLookAndFeel.install();

        JPanel mainPanel = new JPanel();
        mainPanel.setLayout(new BoxLayout(mainPanel, BoxLayout.PAGE_AXIS));

        final ButtonModel model1 = new JToggleButton.ToggleButtonModel();
        model1.setSelected(true);
        final JRadioButton button1 = new JRadioButton();
        button1.setModel(model1);

        final ButtonModel model2 = new JToggleButton.ToggleButtonModel();
        model2.setSelected(true);
        final JRadioButton button2 = new JRadioButton();
        button2.setModel(model2);

        final ButtonModel model3 = new JToggleButton.ToggleButtonModel();
        model3.setSelected(true);
        final JCheckBox button3 = new JCheckBox();
        button3.setModel(model3);

        mainPanel.add(button1);
        mainPanel.add(button2);
        mainPanel.add(button3);
        add(mainPanel);

        setSize(200, 300);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
    }


    public static void main(String[] args) {

        EventQueue.invokeLater(() -> {
            Test ex = new Test();
            ex.setVisible(true);
        });
    }

}
```

**Comment by iMichka** [comment] 2016-07-25 15:14
There is a second thing that may be related to this bug:

```
import com.alee.laf.WebLookAndFeel;

import javax.swing.*;
import java.awt.*;

public class Test extends JFrame {

    private Test() {
        initUI();
    }

    private void initUI() {

        WebLookAndFeel.install();

        final JMenuBar jMenuBar = new JMenuBar();
        final JMenu menu = new JMenu("A Menu");
        jMenuBar.add(menu);
        setJMenuBar(jMenuBar);

        final ButtonModel model = new JToggleButton.ToggleButtonModel();
        model.setSelected(true);
        final JCheckBoxMenuItem jCheckBoxMenuItem = new JCheckBoxMenuItem("Test");
        jCheckBoxMenuItem.setModel(model);
        menu.add(jCheckBoxMenuItem);

        setSize(200, 300);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
    }
    
    public static void main(String[] args) {

        EventQueue.invokeLater(() -> {
            Test ex = new Test();
            ex.setVisible(true);
        });
    }
}
```

In that case the check on the checkbox is only painted if you move the mouse over the checkbox, whereas the check is painted directly when not using WebLaf.

**Comment by mgarin** [comment] 2016-07-25 15:26
I can confirm this can be easily reproduced and actually with any custom model set after checkbox or radiobutton creation.

I also found the source of this issue - pretty much the cause of this is decoration state not being properly updated for any button in `AbstractButtonPainter` on button model change.

**Comment by mgarin** [comment] 2016-07-25 15:27
I have pushed the fix for this issue, it will be available in snapshot builds slightly later today along with other changes coming soon.

**Closed by mgarin** 2016-07-25 15:27 UTC
Labels: bug, confirmed
