### ISSUE TITLE
Explicit SLF4J Bindings are causing classpath dependency problems.

### ISSUE THREAD

**Issue by EdwardBeckett** [mgarin/weblaf#223] opened 2015-01-31 19:44 UTC
The weblaf jar has an explicit dependency on slf4j instead of slf4j-api which causes classpath conflicts when using any library that uses SLF4J... 
 
---
Found binding in [jar:file:/~/.m2/repository/de/sciss/weblaf-complete/1.28/weblaf-complete-1.28.jar!/org/slf4j/impl/StaticLoggerBinder.class]

---
>
Embedded components such as libraries or frameworks should not declare a dependency on any SLF4J binding but only depend on slf4j-api. When a library declares a compile-time dependency on a SLF4J binding, it imposes that binding on the end-user, thus negating SLF4J's purpose.

**Comment by mgarin** [comment] 2015-02-02 09:08
WebLaF doesn't depend on any classes except slf4j API classes, that is for sure. Also there is only one class in WebLaF that does reference any slf4j classes - it is [`Log`](https://github.com/mgarin/weblaf/blob/master/modules/core/src/com/alee/managers/log/Log.java) class which handles all logging coming from WebLaF library.

Probably the issue is that you are using "complete" WebLaF build instead of separate jars - it does include simple implementation of slf4j. You might just want to get separate WebLaF binaries and libraries it uses to include in your project. In that way you will be able to control slf4j implementation and other dependencies as well.

Check this description for more information on different binaries: https://github.com/mgarin/weblaf#artifacts

**Comment by EdwardBeckett** [comment] 2015-02-02 23:29
@mgarin You're probably correct ~ I installed the uber jar... didn't think about the dep on ~/slf4j/impl/StaticLoggerBinder ...

**Comment by mgarin** [comment] 2015-02-03 09:00
I would recommend you to pick these binaries:
- [**weblaf-core-1.28.jar**](https://github.com/mgarin/weblaf/releases/download/v1.28/weblaf-core-1.28.jar) - library core part jar, contains only WebLaF core classes
- [**weblaf-ui-1.28.jar**](https://github.com/mgarin/weblaf/releases/download/v1.28/weblaf-ui-1.28.jar) - library UI part jar, contains only WebLaF UI classes

And these dependencies:
- [**slf4j-api-1.7.7.jar**](https://github.com/mgarin/weblaf/raw/master/lib/slf4j-api-1.7.7.jar) - Logger used by all WebLaF classes
- [**xstream-1.4.7.jar**](https://github.com/mgarin/weblaf/raw/master/lib/xstream-1.4.7.jar) - Used by various WebLaF managers and utilities
- [**jericho-html-3.3.jar**](https://github.com/mgarin/weblaf/raw/master/lib/jericho-html-3.3.jar) - Used by HtmlUtils and some other classes
- [**java-image-scaling-0.8.5.jar**](https://github.com/mgarin/weblaf/raw/master/lib/java-image-scaling-0.8.5.jar) - Used for smooth image scaling

Those should be sufficient for WebLaF to function properly and will also allow you to provide custom slf4j implementation instead of simple one.

Will close this issue for now, but feel free to reopen it if you will encounter any issues.

**Closed by mgarin** 2015-02-03 09:00 UTC
Labels: question

**Comment by EdwardBeckett** [comment] 2015-02-03 10:04
Thanks mgarin :+1 Love the LAF :)
