### ISSUE TITLE
File chooser breaks JSpinner keyboard shortcuts

### ISSUE THREAD

**Issue by Sciss** [mgarin/weblaf#118] opened 2014-05-08 13:19 UTC
The initialization of the `FileChooserUI` introduces a weird bug: Some keyboard short cuts seem to get broken. I have reproduced this with `JSpinner` which ceases to react to the <tt>Enter</tt> after a `JFileChooser` is created.

```java
package de.sciss.foo;

import javax.swing.*;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import java.awt.*;

public class WebLaFBug implements Runnable {
    public WebLaFBug() {}

    public static void main(String[] args) {
        EventQueue.invokeLater(new WebLaFBug());
    }

    public void run() {
        try {
            String web = "com.alee.laf.WebLookAndFeel";
            UIManager.installLookAndFeel("Web Look And Feel", web);
            UIManager.setLookAndFeel(web);
        } catch(Exception e) {
            e.printStackTrace();
        }

        new JFileChooser();  // !

        JSpinner s = new JSpinner(new SpinnerNumberModel(1, 1, 0x7FFFFFFF, 1));
        s.addChangeListener(new ChangeListener() {
            public void stateChanged(ChangeEvent e) {
                System.out.println("Change!");
            }
        });

        JFrame f = new JFrame();
        f.getContentPane().add(s);
        f.pack();
        f.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        f.setVisible(true);
    }
}
```

If you run this example, you can see that if you type a number in the spinner and hit <tt>Enter</tt>, nothing happens. If you remove the line `new JFileChooser();`, the spinner correctly notices when one pressed <tt>Enter</tt>.

----

As a work-around, if I create a dummy `JSpinner` as the first action within my application, the keymap is preserved.

**Comment by mgarin** [comment] 2016-05-13 17:38
It seems that this issue had some shady connection with `UIManager` initialization which wasn't called properly, but I'm not sure at this point. 

Right now this issue seems to be gone - I've tried to reproduce it on different examples and were not able to. I'll be closing this issue, but if it ever appears again - reopen it and I will investigate it again.

**Closed by mgarin** 2016-05-13 17:38 UTC
Labels: bug, confirmed

**Comment by mgarin** [comment] 2017-06-05 15:22
Just a short note - I have completely removed workaround for this issue from the `WebLookAndFeel` class code as it is not necessary anymore and would only provoke different issues. This change will soon be available along with the other improvements in `styling` branch code.

Events are working as intended now and the bug cannot be reproduced anymore. Though if the issue ever appears again - feel free to reopen this ticket.
