### ISSUE TITLE
Decorated dialog can't restore

### ISSUE THREAD

**Issue by charghet** [mgarin/weblaf#642] opened 2020-08-22 11:17 UTC
java 1.8.0 u221 windows10
I restore the demo when I show a decorated dialog from the demo and minimize the demo, but the decorated dialog can not visit and I can't press the second "show dialog" button, it seems that the decorated dialog has been hidden. I use a screenshot software can see the hidden decorated dialog. The basic dialog won't be like this.
![image](https://user-images.githubusercontent.com/48718659/90954804-5fbcbf80-e4aa-11ea-8188-79b3e67a6f3b.png)

**Comment by mgarin** [comment] 2020-12-11 15:23
Regarding the original issue -
After some further digging I found that the same issue appears with any L&F and seems to be JDK-related:
https://bugs.openjdk.java.net/browse/JDK-8187603

I have also tried to reproduced it again after recent changes and it doesn't seem to happen for on WebLaF demo anymore, but it does happen on the example from the bug report I've linked above. This is certainly something system/JDK-related and I don't think I'll be able to fix this in WebLaF anyhow.

I'll keep this issue open, but will move it to JDK-related project and tag it appropriately.

**Comment by mgarin** [comment] 2020-12-11 15:28
In fact, I'll be closing it since it was mentioned in the issue that it doesn't appear on Java 9 or later and won't be fixed in 7/8 versions. For those, as explained in the linked issue, you can simply hide the dialog whenever frame is minimized to avoid this bug. Although this isn't something I would want to add in WebLaF code as it might negatively affect other library users.

**Closed by mgarin** 2020-12-11 15:28 UTC
Labels: bug, confirmed, workaround
