### ISSUE TITLE
Erease text with keyboard (DEL, BACKSPACE) not Working on WebFormattedTextField.

### ISSUE THREAD

**Issue by agusdutra** [mgarin/weblaf#475] opened 2017-11-23 20:05 UTC
I've update to latest version, 1.29, and this stopped working.

I have editable textfields that can receive text inputs with no problem, but when I want to edit the content with BACKSPACE or DELETE, it doen't work.
If I select all the text and replace with new one, it works OK, but this is not the desired behaviour.

**Comment by mgarin** [comment] 2017-11-24 01:51
Where exactly did you download the 1.29? 
As there are a few options available until the final release and some might actually be buggy.

I recommend trying out the one that builds straight from latest `styling` branch code:
https://oss.sonatype.org/content/repositories/snapshots/com/weblookandfeel/
You can find separate jars there (`core` and `ui`, and `plugin` if needed) and add dependency libraries on top of them. 

As an alternative you can also use those artifacts through attaching `ui` module as maven project dependency.

**Comment by mgarin** [comment] 2017-11-24 01:52
Regarding the issue - I tried `WebTextField` on the latest `styling` version and I cannot reproduce it, so probably you are using one of the older versions which still had some major flaws.

**Comment by agusdutra** [comment] 2017-11-24 14:15
Thanks for the response.
I'm using version 1.29-complete downloaded from weblookandfeel.com

Right now I can't update to this last branch becuase it has a lot of breaking changes regarding the styling. 
And I won't like to go back to previous version because in this version you solved a lot of memory leak issues that were affecting our production app.

Sorry for the mistake, but this issue is happening with **WebFormattedTextField**.
It's like the events for keys Backspace, and the arrows to move between the text are not being processed by the JTextField behind.

i also tried to downgrade to 1.28 and this is happening also. 
Maybe I could get a workaround to customize these behaviour.

Thanks.

**Comment by mgarin** [comment] 2017-11-27 08:51
I tried quite a few versions including the one that is currently available on the site:
http://weblookandfeel.com/downloads/prerelease/weblaf-complete-1.29.jar
And wasn't able to reproduce the bug.

It might be something tied to specific JDK version or OS, could you specify which exact JDK and OS versions do you have where that issue appears?

Also, does this happen for you in the demo application?
This one: http://weblookandfeel.com/downloads/prerelease/weblaf-demo-1.29.jar
If not - then it is most probably something that messes with default hotkeys in your specific application, for instance a global AWT listener that consumes events for backspace and arrows.

**Comment by mgarin** [comment] 2017-12-11 12:01
@agusdutra I'll leave this issue open, but unconfirmed as I cannot really reproduce this on any of the versions/OS I tried. Leave some more information whenever you will be able to and I'll investigate it again.

**Comment by agusdutra** [comment] 2017-12-11 15:34
Thanks for your answer. 
It was a production problem on a project that is on mantainance. 
I updated to the 1.29 because of the memory leaks we were facing, but this other problem started. 
It may be something with our implementation. The temporary solution we found was going back to version 1.27, that has less memory leaks than 1.26. - (This editor problem happened with the 1.28 also)

On the next days I will try to check this again, and I will let you know. 
Thanks

**Comment by mgarin** [comment] 2017-12-11 16:36
Thanks for the followup! I'll be waiting for more information.

On the memory leaks topic - I've recently eradicated dozens of them in `styling` branch code and completely changed the approach taken for places in the code that could cause memory leaks in general. So there is a high chance that the latest `styling` branch versions doesn't have any more leaks. We've only confirmed that on our internal projects, but we don't use every single small feature in the library so it is hard to say for sure, time will show.

I do remember that you can't easily update to newer version right now, but at the same time, unfortunately, I cannot copy most of the changes into older versions - that includes these recent memory leak fixes - due to huge code difference (mostly due to internal structure difference). Porting those changes would simply take too much time and for some cases isn't even worth the effort. So I do recommend switching to newer version whenever it will become possible if you want to receive all updates and fixes without any exceptions.

**Comment by agusdutra** [comment] 2017-12-11 17:37
Yes, I've noticed that there are a lot of changes, so it isn't easy to us to update to the newer version, but we know that it's the right thing to do. 
Does that branch has any official release date or estimate? 
Thanks

**Comment by mgarin** [comment] 2017-12-11 18:11
Can't call a specific date as it never worked before with this particular update due to its size and multiple complications I've encountered along the way while trying to bend/fix Swing problems.

That being said, there are only a few major things left ( #476 ) and a bunch of minor issues and patches I need to make before release, so I'm quite positive that it might happen soon enough.

For more specific information on "whats left?" you can track this project page:
https://github.com/mgarin/weblaf/projects/1

Some minor things that are remaining might even be moved to the next update if those will be hard to implement without doing some major changes as I don't want to stretch this update even further.

**Comment by mgarin** [comment] 2019-08-05 14:01
I'll be closing this issue since I cannot reproduce the original problem.
All the memory leaks should now be fixed in v1.2.9 update:
https://github.com/mgarin/weblaf/releases/tag/v1.2.9

**Closed by mgarin** 2019-08-05 14:01 UTC
Labels: bug
