### ISSUE TITLE
NPE in WebFileChooserPanel.setSelectedFile:1233

### ISSUE THREAD

**Issue by renato** [mgarin/weblaf#271] opened 2015-04-22 17:32 UTC
When we setFileFilter() in a JFileChooser but the currently selected file isn't accepted by this new file filter, JFileChooser sets the file to null (JFileChooser.java:1469):
```
            } else if (selectedFile != null && !filter.accept(selectedFile)) {
                setSelectedFile(null);
            }
```

This causes a NPE because the setSelectedFile() in WebFileChooserPanel checks if the file exists without checking the file nullity.

**Comment by mgarin** [comment] 2015-05-05 10:18
I tried to reproduce issue with this code:
```java
public class Test
{
    public static void main ( final String[] args )
    {
        WebLookAndFeel.install ();

        final JFileChooser fileChooser = new JFileChooser (  );
        fileChooser.setFileFilter ( new javax.swing.filechooser.FileFilter ()
        {
            @Override
            public boolean accept ( final File f )
            {
                return false;
            }

            @Override
            public String getDescription ()
            {
                return "Test";
            }
        } );
        fileChooser.setSelectedFile ( new File ( "C:\\test.txt" ) );
        fileChooser.showDialog ( null, "Choose" );
    }
}
```
It works properly.
And if I remove filter - file will be properly selected in the file chooser.

Could you provide an example that reproduces this issue?

**Comment by renato** [comment] 2015-05-05 16:01
Using your same code:
```java
public class Test
{
    public static void main ( final String[] args )
    {
        WebLookAndFeel.install();

        final JFileChooser fileChooser = new JFileChooser (  );
        fileChooser.setSelectedFile ( new File ( "C:\\test.txt" ) );
        fileChooser.setFileFilter(new javax.swing.filechooser.FileFilter() {
            @Override
            public boolean accept(final File f) {
                return false;
            }

            @Override
            public String getDescription() {
                return "Test";
            }
        });

        fileChooser.showDialog(null, "Choose");
    }
}
```

I just inverted the order (setSelectedFile first, then setFileFilter).

Got this NPE:
```
Exception in thread "main" java.lang.NullPointerException
	at com.alee.laf.filechooser.WebFileChooserPanel.setSelectedFile(WebFileChooserPanel.java:1233)
	at com.alee.laf.filechooser.WebFileChooserUI.propertyChanged(WebFileChooserUI.java:325)
	at com.alee.laf.filechooser.WebFileChooserUI$3.propertyChange(WebFileChooserUI.java:156)
	at java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:335)
	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:327)
	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:263)
	at java.awt.Component.firePropertyChange(Component.java:8422)
	at javax.swing.JFileChooser.setSelectedFile(JFileChooser.java:508)
	at javax.swing.JFileChooser.setFileFilter(JFileChooser.java:1470)
	at Test.main(Test.java:14)
```

**Comment by renato** [comment] 2015-05-05 16:06
Just to be clear, the real issue is that the JFileChooser is forcing a setSelectedFile(null) and WebLAF throws a NPE because it doesn't check the attribute nullity.

The real problem here is that a setSelectedFile(null) is accepted by Swing, but throws a NPE with WebLAF. In other words, the NPE would happen in a codebase which uses this same setSelectedFile(null) for some reason.

**Comment by mgarin** [comment] 2015-05-05 18:35
Well, I checked the `setSelectedFile` method calls chain first and how it performs - it was working properly. Then I tried the case in which you were getting this issue and weren't able to reproduce it.

I also tried the other example you've shown (with inverted order) just now and it is still working properly for me. Probably you are using older (v1.28) WebLaF version? It might have this issue indeed since a lot of things were actually changed.

If that is the case - can you try this example with pre-release v1.29?
You can find the latest pre-release artifacts here: http://weblookandfeel.com/downloads/prerelease/

**Comment by renato** [comment] 2015-05-05 18:49
No need to test, you are right. WebFileChooserPanel now checks if the file is null:
https://github.com/mgarin/weblaf/blob/master/modules/ui/src/com/alee/laf/filechooser/WebFileChooserPanel.java#L1403

Actually this is a pretty old commit: https://github.com/mgarin/weblaf/commit/ff99e20a3c277e788a6681766d64fd4a570dbc38

I didn't realize that v1.28 was so old, I was avoiding the "pre-release" artifacts but I think I should consider updating. :)

Sorry about this issue, it can be closed.

**Comment by mgarin** [comment] 2015-05-05 18:51
Yep, v1.28 is pretty old and, actually, pre-release v1.29 is much more stable.
I just weren't able to complete all of the v1.29 goals to release it yet.

**Comment by mgarin** [comment] 2015-05-05 18:51
I'll close this one then.

**Closed by mgarin** 2015-05-05 18:51 UTC
Labels: bug
