### ISSUE TITLE
FileChooser using 100% CPU

### ISSUE THREAD

**Issue by iMichka** [mgarin/weblaf#310] opened 2015-06-29 13:53 UTC
Hi

when opening a fileChooser it uses 100% of one CPU. This is under Ubuntu 12.04 and Java 6. Is there something I can do to debug this (maybe some prints at the right place to see what exactly is permanently called) ?

Thanks in advance.

**Comment by mgarin** [comment] 2015-06-29 14:11
As I understand - this is a permanent issue that appears **after** loading the chooser, right?
Is the UI of the chooser still responsive? Or is it lagging / not responding?
What is the exact Java version (update) / type (oracle/openjdk) you are using?

**Comment by iamchathu** [comment] 2015-06-29 14:13
Same in Windows 8.1 Java 7. There is delay when loading file chooser.

**Comment by iMichka** [comment] 2015-06-29 14:26
In my case the fileChooser is still responsive and I have no direct GUI problem with it. (But we would like to keep the processor usage low for other things).

The java version is 1.6.0_26-b03

**Comment by Sciss** [comment] 2015-06-29 14:28
Depending on your IDE, you can figure out which threads are eating CPU. In IntelliJ IDEA this is super-easy. When you run your application from the IDE, at the point where file chooser is open, press the thread-dump button (photo camera icon).

**Comment by mgarin** [comment] 2015-06-30 08:16
Thanks for pointing out this issue, I was able to find out the source.
Fix will soon be available.

**Comment by mgarin** [comment] 2015-06-30 09:06
I have added a fix for this issue - it should almost nullify CPU load and should also slightly increase image thumbnails generation speed. Problem was caused by constant thumbnails generation which occurred due to lack of a few stop-checks.

I can't really add this fix into master right now, but I have updated v1.29 pre-release build:
http://weblookandfeel.com/downloads/prerelease/
This build also includes the fix for popup menus transparency from the `styling` branch.

Code for this fix will be added later this week into `styling` branch along with a lot of other changes.

**Comment by iMichka** [comment] 2015-07-02 08:42
Hi. We also found out that the thumbnail refreshing was called too much. That would explain it, and also why it was getting slow for some users when there were a lot of images to refresh.

I will not have time to test this now, going 1 week on holidays. I'm coming back around the 13th July, then I will test it again from the styling branch, if you have time to push your fix. Thanks for all.

**Comment by mgarin** [comment] 2015-07-02 08:47
Those changes will surely be in `styling` before 13th July, but I am not sure in what state will the branch be there. You might just test the pre-release build since the branch is unstable in other aspects and might interfere with tests with its own issues I am working on right now.

**Comment by iMichka** [comment] 2015-07-15 06:41
Hi
I gave it a try with the demo (current master demo vs the pre-release build) and the processor usage stays low. Good work here. Thanks for the fix.

**Comment by mgarin** [comment] 2015-07-17 12:09
Glad to hear that!

**Closed** 2016-05-13 14:23 UTC
Labels: bug, confirmed, solved
